name: Build
on: 
  push:
    branches:
      - master
      - main
      - tmp-*
    tags:
      - v*
  pull_request:

jobs:
  honesty:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          make setup
          pip install -U .
      - name: Test
        run: make test
      - name: Lint
        run: make lint
